mod accounts;
mod ea_version;
mod install_ctrader;
mod install_mt;
mod quotes;
mod rules;
mod settings;
mod util;

// Glob-export so the `__cmd__*` symbols generated by `#[tauri::command]`
// resolve as `commands::__cmd__name` (what `generate_handler!` expects).
pub use accounts::*;
pub use ea_version::*;
pub use install_ctrader::*;
pub use install_mt::*;
pub use quotes::*;
pub use rules::*;
pub use settings::*;

// Connector code (mt_bridge) reaches in for these directly.
pub(crate) use install_mt::mt_common_dirs;
